# Import all constants
from .request_context import (
    REQUEST_CONTEXT_HEADER,
    AUTONOMOUS_EXECUTION_HEADER,
    REQUEST_CONTEXT_PROMPT,
    WORK_DIR_USAGE,
)
from .file_handling import (
    UPLOAD_MARKER_INSTRUCTIONS,
    FILE_VERIFICATION_INSTRUCTIONS,
    BASE64_FORBIDDEN,
    FILE_HANDLING_GUIDANCE,
    FILE_HANDLING_RULES,
)
from .forbidden_patterns import (
    FORBIDDEN_PHRASES_COMPONENT,
    RESPONSE_TONE_GUIDANCE,
    FORBIDDEN_FILLER_LANGUAGE,
    FORBIDDEN_INTERNAL_TERMINOLOGY,
    FORBIDDEN_CORPORATE_LANGUAGE,
    OUTPUT_FORMATTING_GUIDANCE,
    VISUAL_REQUIREMENTS_GUIDANCE,
    TASK_COMPLEXITY_GUIDANCE,
    AUTONOMOUS_OPERATION_GUIDELINES,
)
from .data_validation import (
    EMPTY_DATA_VALIDATION_CODER,
    EMPTY_DATA_VALIDATION_PRESENTER,
    FACTUAL_ACCURACY_VALIDATION,
    LLM_DATA_VALIDATION_FRAMEWORK,
)
from .progress_frameworks import (
    PROGRESS_LOGGING_FRAMEWORK,
)
from .error_frameworks import (
    ERROR_RECOVERY_FRAMEWORK,
    ERROR_HANDLING_PATTERNS,
    UNIVERSAL_SELF_CORRECTION_FRAMEWORK,
)
from .data_frameworks import (
    JSON_PREVIEW_FRAMEWORK,
    DATA_SAVING_FRAMEWORK,
    DATA_VALIDATION_FRAMEWORK,
    get_data_validation_framework,
)
from .validation_frameworks import (
    SEQUENCE_VALIDATION_FRAMEWORK,
)
from .guidance_frameworks import (
    BASE_AUTONOMOUS_OPERATION,
    KEY_INSIGHTS_GUIDANCE,
)
from .planning_frameworks import (
    PLANNING_PHASE_REQUIREMENTS,
    PLANNER_SPECIFIC_GUIDANCE,
    OUTPUT_FORMAT_REQUIREMENTS,
    STRATEGIC_AGENT_SELECTION,
    DEPENDENCY_GUARDRAILS,
    API_CREDENTIAL_AWARENESS,
    FLEXIBLE_WORKFLOW_DESIGN,
    ADAPTIVE_STRATEGIES,
    CONTEXT_AWARE_PLANNING,
    CONTINUOUS_COLLABORATION,
    PLANNING_QUALITY_FRAMEWORK,
    VISUAL_GUIDANCE_PLANNING,
    VALUE_CREATION_FRAMEWORK,
    DELIVERABLE_LINK_POLICY,
)
from .workflow_frameworks import (
    CIRCUIT_BREAKER_GUIDANCE,
    FILE_CONTRACT_GUIDANCE,
    WORKFLOW_COORDINATION_GUIDANCE,
    DATA_QUALITY_GUIDANCE,
    ERROR_RECOVERY_GUIDANCE,
    TOOL_FAILURE_DETECTION_GUIDANCE,
    TIMEOUT_HANDLING_GUIDANCE,
    LOOP_DETECTION_GUIDANCE,
)
from .tool_response_analysis import (
    TOOL_RESPONSE_ANALYSIS_FRAMEWORK,
    WEB_SEARCH_AGENT_STATUS_ANALYSIS,
    DATA_SOURCE_FALLBACK_FRAMEWORK,
    INTER_AGENT_COMMUNICATION_PROTOCOL,
)
from .transparent_status_reporting import (
    TRANSPARENT_STATUS_REPORTING_FRAMEWORK,
    WEB_SEARCH_TRANSPARENT_REPORTING,
    CODER_AGENT_TRANSPARENT_REPORTING,
    UPLOAD_TRANSPARENT_REPORTING,
)
from .agent_coordination import (
    AGENT_COORDINATION_PROTOCOL,
    AGENT_ROUTING_INTELLIGENCE,
    AGENT_FAILURE_RECOVERY,
    CONTEXT_MEMORY_PROTOCOL,
    WORKFLOW_ORCHESTRATION,
)
from .code_execution import (
    CODE_EXECUTION_CORE,
    DATA_QUALITY_REQUIREMENTS,
    SCOPE_AWARENESS_GUIDANCE,
    VISUALIZATION_GUIDANCE,
    EXECUTION_PATTERNS,
    COMPLETION_CRITERIA,
)
from .data_processing import (
    DATA_COMPLETENESS_ACCURACY,
    INPUT_VALIDATION_RULES,
    DATA_PROCESSING_GUIDANCE,
    FILE_DISCOVERY_LOGIC,
    DATA_FILE_PARSING,
    HTML_DATA_EXTRACTION,
    DOWNLOAD_FAILURE_HANDLING,
    LOOP_PREVENTION,
    GENERIC_DATA_STRATEGY,
    WORKSPACE_STATE_AWARENESS,
    EMPTY_DATA_FILE_PREVENTION,
    DATE_RANGE_FILTERING_CLEAN_FAILURE,
)
from .file_generation import (
    GENERIC_FILE_GENERATION_INTELLIGENCE,
    MULTI_FORMAT_SUPPORT,
    PDF_GENERATION_REQUIREMENTS,
    PRESENTATION_FLOW_REQUIREMENTS,
    DUPLICATE_PREVENTION,
    URL_VALIDATION,
    WORD_CLOUD_GENERATION,
    COMPLEX_TASK_HANDLING,
    DYNAMIC_CONTEXT_PARSING,
    AGENT_COLLABORATION_PROTOCOL,
    CLEAN_ERROR_HANDLING,
    REMOTE_ASSET_PRE_DOWNLOAD_PROTOCOL,
    SMART_IMAGE_PREVIEW_PROCESSING,
    FILE_LISTING_CLEANLINESS,
    IMAGE_DISTRIBUTION_GUIDANCE,
    POWERPOINT_CREATION_ROBUSTNESS,
    OUTPUT_FORMAT_GUIDANCE,
)
from .agent_intelligence import (
    AGENT_INTELLIGENCE_CORE,
    TOOL_RESPONSE_INTELLIGENCE,
    STRATEGIC_ADAPTATION,
    INTELLIGENT_RECOVERY,
    AGENT_COMMUNICATION_INTELLIGENCE,
)
from .global_quality_standards import (
    GLOBAL_QUALITY_EXPECTATIONS,  # Shared source of truth for execution_completion_verifier_agent and test scoring system
    format_global_expectations_for_agent,
)
from .visual_processing import (
    IMAGE_AND_PDF_PROCESSING_CAPABILITIES,
)
from .output_principles import (
    OUTPUT_ONLY_FINAL_RESULTS_PRINCIPLE,
    DEPENDENCY_WAITING_PRINCIPLE,
)
from .requirement_extraction import (
    UNIVERSAL_REQUIREMENT_EXTRACTION_FRAMEWORK,
)

__all__ = [
    # Request context
    'REQUEST_CONTEXT_HEADER',
    'AUTONOMOUS_EXECUTION_HEADER',
    'REQUEST_CONTEXT_PROMPT',
    'WORK_DIR_USAGE',
    # File handling
    'UPLOAD_MARKER_INSTRUCTIONS',
    'FILE_VERIFICATION_INSTRUCTIONS',
    'BASE64_FORBIDDEN',
    'FILE_HANDLING_GUIDANCE',
    'FILE_HANDLING_RULES',
    # Forbidden patterns
    'FORBIDDEN_PHRASES_COMPONENT',
    'RESPONSE_TONE_GUIDANCE',
    'FORBIDDEN_FILLER_LANGUAGE',
    'FORBIDDEN_INTERNAL_TERMINOLOGY',
    'FORBIDDEN_CORPORATE_LANGUAGE',
    'OUTPUT_FORMATTING_GUIDANCE',
    'VISUAL_REQUIREMENTS_GUIDANCE',
    'TASK_COMPLEXITY_GUIDANCE',
    'AUTONOMOUS_OPERATION_GUIDELINES',
    # Data validation
    'EMPTY_DATA_VALIDATION_CODER',
    'EMPTY_DATA_VALIDATION_PRESENTER',
    'FACTUAL_ACCURACY_VALIDATION',
    'LLM_DATA_VALIDATION_FRAMEWORK',
    # Progress frameworks
    'PROGRESS_LOGGING_FRAMEWORK',
    # Error frameworks
    'ERROR_RECOVERY_FRAMEWORK',
    'ERROR_HANDLING_PATTERNS',
    'UNIVERSAL_SELF_CORRECTION_FRAMEWORK',
    # Data frameworks
    'JSON_PREVIEW_FRAMEWORK',
    'DATA_SAVING_FRAMEWORK',
    'DATA_VALIDATION_FRAMEWORK',
    # Validation frameworks
    'SEQUENCE_VALIDATION_FRAMEWORK',
    # Guidance frameworks
    'BASE_AUTONOMOUS_OPERATION',
    'KEY_INSIGHTS_GUIDANCE',
    'DATA_QUALITY_GUIDANCE',
    "ERROR_RECOVERY_GUIDANCE",
    # Planning frameworks
    'PLANNING_PHASE_REQUIREMENTS',
    'PLANNER_SPECIFIC_GUIDANCE',
    'OUTPUT_FORMAT_REQUIREMENTS',
    'STRATEGIC_AGENT_SELECTION',
    'DEPENDENCY_GUARDRAILS',
    'API_CREDENTIAL_AWARENESS',
    'FLEXIBLE_WORKFLOW_DESIGN',
    'ADAPTIVE_STRATEGIES',
    'CONTEXT_AWARE_PLANNING',
    'CONTINUOUS_COLLABORATION',
    'PLANNING_QUALITY_FRAMEWORK',
    'VISUAL_GUIDANCE_PLANNING',
    'VALUE_CREATION_FRAMEWORK',
    'DELIVERABLE_LINK_POLICY',
    # Workflow frameworks
    'CIRCUIT_BREAKER_GUIDANCE',
    'FILE_CONTRACT_GUIDANCE',
    'WORKFLOW_COORDINATION_GUIDANCE',
    'TOOL_FAILURE_DETECTION_GUIDANCE',
    'TIMEOUT_HANDLING_GUIDANCE',
    'LOOP_DETECTION_GUIDANCE',
    # Tool response analysis
    'TOOL_RESPONSE_ANALYSIS_FRAMEWORK',
    'WEB_SEARCH_AGENT_STATUS_ANALYSIS',
    'DATA_SOURCE_FALLBACK_FRAMEWORK',
    'INTER_AGENT_COMMUNICATION_PROTOCOL',
    # Transparent status reporting
    'TRANSPARENT_STATUS_REPORTING_FRAMEWORK',
    'WEB_SEARCH_TRANSPARENT_REPORTING',
    'CODER_AGENT_TRANSPARENT_REPORTING',
    'UPLOAD_TRANSPARENT_REPORTING',
    # Agent coordination
    'AGENT_COORDINATION_PROTOCOL',
    'AGENT_ROUTING_INTELLIGENCE',
    'AGENT_FAILURE_RECOVERY',
    'CONTEXT_MEMORY_PROTOCOL',
    'WORKFLOW_ORCHESTRATION',
    # Code execution
    'CODE_EXECUTION_CORE',
    'DATA_QUALITY_REQUIREMENTS',
    'SCOPE_AWARENESS_GUIDANCE',
    'VISUALIZATION_GUIDANCE',
    'EXECUTION_PATTERNS',
    'COMPLETION_CRITERIA',
    # Data processing
    'DATA_COMPLETENESS_ACCURACY',
    'INPUT_VALIDATION_RULES',
    'DATA_PROCESSING_GUIDANCE',
    'FILE_DISCOVERY_LOGIC',
    'WORKSPACE_STATE_AWARENESS',
    'DATA_FILE_PARSING',
    'HTML_DATA_EXTRACTION',
    'DOWNLOAD_FAILURE_HANDLING',
    'LOOP_PREVENTION',
    'GENERIC_DATA_STRATEGY',
    'EMPTY_DATA_FILE_PREVENTION',
    'DATE_RANGE_FILTERING_CLEAN_FAILURE',
    # File generation
    'GENERIC_FILE_GENERATION_INTELLIGENCE',
    'MULTI_FORMAT_SUPPORT',
    'PDF_GENERATION_REQUIREMENTS',
    'PRESENTATION_FLOW_REQUIREMENTS',
    'DUPLICATE_PREVENTION',
    'URL_VALIDATION',
    'WORD_CLOUD_GENERATION',
    'COMPLEX_TASK_HANDLING',
    'DYNAMIC_CONTEXT_PARSING',
    'AGENT_COLLABORATION_PROTOCOL',
    'CLEAN_ERROR_HANDLING',
    'REMOTE_ASSET_PRE_DOWNLOAD_PROTOCOL',
    'SMART_IMAGE_PREVIEW_PROCESSING',
    'FILE_LISTING_CLEANLINESS',
    'IMAGE_DISTRIBUTION_GUIDANCE',
    'POWERPOINT_CREATION_ROBUSTNESS',
    'OUTPUT_FORMAT_GUIDANCE',
    # Agent intelligence
    'AGENT_INTELLIGENCE_CORE',
    'TOOL_RESPONSE_INTELLIGENCE',
    'STRATEGIC_ADAPTATION',
    'INTELLIGENT_RECOVERY',
    'AGENT_COMMUNICATION_INTELLIGENCE',
    # SQL query handling
    # Global quality standards
    'GLOBAL_QUALITY_EXPECTATIONS',
    'format_global_expectations_for_agent',
    # Visual processing
    'IMAGE_AND_PDF_PROCESSING_CAPABILITIES',
    # Output principles
    'OUTPUT_ONLY_FINAL_RESULTS_PRINCIPLE',
    'DEPENDENCY_WAITING_PRINCIPLE',
    # Requirement extraction
    'UNIVERSAL_REQUIREMENT_EXTRACTION_FRAMEWORK',
]
