export default {
    prompt: "",
    model: "azure-video-translate",
    enableDuplicateRequests: false,
    inputParameters: {
      mode: "",
      apiversion: "",
      region: "",
      subscriptionkey: "",
      id: "",
      sourcelocale: "",
      targetlocale: "",
      targetlocales: "",
      videooraudiofileid: "",
      sourcevideooraudiofilepath: "",
      webvttsourcekind: "",
      sourcelocalewebvttfilepath: "",
      targetlocalewebvttfilepath: "",
      voicekind: "",
      deleteassociations: "",
      reuseexistingvideooraudiofile: "",
      withoutsubtitleintranslatedvideofile: "",
      subtitlemaxcharcountpersegment: "",
      exportpersonalvoicepromptaudiometadata: "",
      personalvoicemodelname: "",
      isassociatedwithtargetlocale: "",
      additionalhttpheaders: "",
      enablefeatures: "",
      profilename: "",
      createtranslationadditionalproperties: "",
    },
    enableCache: false,
  };