module.exports = {
    "pass": require("./pass"),
    "bias": require('./bias'),
    "complete": require('./complete'),
    "entities": require('./entities'),
    "grammar": require('./grammar'),
    "headline": require('./headline'),
    "keywords": require('./keywords'),
    "paraphrase": require('./paraphrase'),
    "sentiment": require('./sentiment'),
    "spelling": require('./spelling'),
    "styleguide": require('./styleguide'),
    "styleguidemulti": require('./styleguidemulti'),
    "summary": require('./summary'),
    "topics": require('./topics'),
    "translate": require('./translate'),
    "translate_td3": require('./translate_td3'),
}