module.exports = {
    "pass": require("./pass"),
    "chat_archie": require('./chat_archie'),
    "chat_context": require('./chat_context'),
    "chat_code": require('./chat_code'),
    "bias": require('./bias'),
    "complete": require('./complete'),
    "entities": require('./entities'),
    "grammar": require('./grammar'),
    "headline": require('./headline'),
    "keywords": require('./keywords'),
    "paraphrase": require('./paraphrase'),
    "sentiment": require('./sentiment'),
    "select_services": require('./select_services'),
    "spelling": require('./spelling'),
    "styleguide": require('./styleguide'),
    "styleguidemulti": require('./styleguidemulti'),
    "summary": require('./summary'),
    "tags": require('./tags'),
    "topics": require('./topics'),
    "translate": require('./translate'),
    "translate_context": require('./translate_context'),
}