export default {
  prompt: ["{{{text}}}"],

  inputParameters: {
    text: "",
    model: "replicate-qwen3-tts",
    mode: "custom_voice",
    language: "auto",
    speaker: "Serena",
    referenceAudio: "",
    referenceAudioUrl: "",
    inputAudioUrl: "",
    audioUrl: "",
    referenceText: "",
    styleInstruction: "",
    voiceDescription: "",
    voice: { type: "string" },
    stability: { type: "number" },
    similarityBoost: { type: "number" },
    style: { type: "number" },
    speed: { type: "number" },
    previousText: { type: "string" },
    nextText: { type: "string" },
    languageCode: { type: "string" },
    voiceId: { type: "string" },
    customVoiceId: { type: "string" },
    volume: { type: "number" },
    pitch: { type: "integer" },
    emotion: { type: "string" },
    audioFormat: { type: "string" },
    sampleRate: { type: "integer" },
    bitrate: { type: "integer" },
    channel: { type: "string" },
    languageBoost: { type: "string" },
    subtitleEnable: { type: "boolean" },
    englishNormalization: { type: "boolean" },
  },

  max_tokens: 8192,
  useInputChunking: false,
  timeout: 60 * 10,
};
