version: '3.4'

services:
  cortex:
    image: arc/whisper
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000


docker tag arc/whisper archipelagoairegistry.azurecr.io/cortex/whisperx

docker push archipelagoairegistry.azurecr.io/cortex/whisperx   