name: Cortex File Handler Tests

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'helper-apps/cortex-file-handler/**'
      - '.github/workflows/cortex-file-handler-test.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'helper-apps/cortex-file-handler/**'
      - '.github/workflows/cortex-file-handler-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    defaults:
      run:
        working-directory: helper-apps/cortex-file-handler
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: helper-apps/cortex-file-handler/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test